name = 'aistock-extapi'
main = "src/index.ts"
compatibility_date = "2026-01-08"
compatibility_flags = ["nodejs_compat"]

[vars]
# 微信公众号 AppID（非敏感，可放 vars）
# WECHAT_APPID = "your_wechat_appid"
# 前端首页地址（登录成功后跳转）
FRONTEND_URL = "https://aistocklink.cn/"
COOKIE_DOMAIN = ".aistocklink.cn"
CORS_ALLOW_ORIGIN = "https://aistocklink.cn"
# 敏感信息请通过 wrangler secret put 设置:
#   wrangler secret put WECHAT_SECRET
#   wrangler secret put JWT_SECRET
#   wrangler secret put WECHAT_APPID  (也可放 secret)

# KV Namespace binding
[[kv_namespaces]]
binding = "KV" 
id = "2e22a1ea7d91471e8476969f8e89ccab"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "aistock"
database_id = "f6efa1f1-4414-491c-a5d6-809fb1adfb8d" # 运行 wrangler d1 create aistock 后填入

[[routes]]
pattern = "extapi.aistocklink.cn"
custom_domain = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[placement]
mode = "smart"