name = 'aistock-extapi'
main = "src/index.ts"
compatibility_date = "2026-01-08"
compatibility_flags = ["nodejs_compat"]

[vars]

# KV Namespace binding
[[kv_namespaces]]
binding = "KV" 
id = "2e22a1ea7d91471e8476969f8e89ccab"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "aistock"
database_id = "087b72de-672c-4d40-9fc8-f90b2146abfc" # 运行 wrangler d1 create aistock 后填入

[[routes]]
pattern = "extapi.aistocklink.cn"
custom_domain = true

# [observability]
# [observability.logs]
# enabled = true
# invocation_logs = true

# [observability.traces]
# enabled = true

[placement]
mode = "smart"