name = 'aistock-extapi'
main = "src/index.ts"
compatibility_date = "2026-01-08"
compatibility_flags = ["nodejs_compat"]

[vars]

# KV Namespace binding
[[kv_namespaces]]
binding = "AISTOCK" 
id = "2e22a1ea7d91471e8476969f8e89ccab"
preview_id = "2e22a1ea7d91471e8476969f8e89ccab" # Optional for local dev

[[routes]]
pattern = "extapi.aistocklink.cn"
custom_domain = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true

[placement]
mode = "smart"